"""Local-Ollama enrichment: per-document summary + tag proposals.

One module, two consumers: the post-ingest auto-summary hook in
``brain.ingest.__init__`` and the interactive ``brain tag --auto`` flow in
``brain.cli``. Both go through :class:`OllamaEnricher` so HTTP transport,
JSON-mode handling, timeouts, and retry policy live in one place.

Ollama is the only backend in Wave Q1-D — no Claude Haiku / OpenAI / Voyage
surface. Model is configurable via ``BRAIN_ENRICH_MODEL`` (default
``llama3.1:8b``). The class reuses the ``httpx.Client`` transport pattern
from :class:`brain.embeddings._OllamaEmbedderBase` but does NOT subclass it:
the embedder hits ``/api/embed`` for vectors and the enricher hits
``/api/chat`` for JSON completions, so a shared parent would carry no
shared logic.

Model upgrade semantics
-----------------------
``documents.summary_model`` records the model fingerprint of every persisted
summary. The post-ingest hook and ``brain enrich --backfill`` both treat
"existing summary AND ``summary_model == cfg.enrich_model``" as up-to-date;
when the user upgrades ``BRAIN_ENRICH_MODEL`` (e.g. ``llama3.1:8b`` →
``llama3.2:8b``), every doc whose stored summary was generated by the OLD
model is automatically re-enriched on next ingest / next backfill run. The
behavior is keyed on ``OllamaEnricher.model`` (the property), so callers
that pass a fake enricher in tests can control the comparison without
monkey-patching the production module.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Any

import httpx
import tiktoken

from .config import Config
from .errors import EnrichmentError, OllamaUnavailable
from .tags import normalize_tags

_logger = logging.getLogger(__name__)

# Module-level keep_alive fallback — matches embeddings.py convention. Tests
# that construct OllamaEnricher without an explicit ``keep_alive`` kwarg get
# this default; production always threads ``Config.ollama_keep_alive``.
_DEFAULT_KEEP_ALIVE = "30m"

# D20 — banned auto-tag formats. These are ``documents.content_type`` values
# (or close synonyms) that the LLM should never propose as semantic tags.
# Belt-and-braces with the prompt: a prompt-injection / model drift case that
# slipped one past the prompt is still filtered at the Python layer. Stored
# casefold-lower-hyphen-normalized so the post-``normalize_tags`` comparison
# is a direct membership check.
_BANNED_AUTO_TAGS = frozenset(
    {
        "pdf",
        "transcript",
        "email",
        "email-thread",
        "note",
        "docx",
        "markdown",
        "text",
        "krisp-action-items",
    }
)


_SUMMARY_SYSTEM_PROMPT = (
    "You write 2-3 sentence summaries of personal-knowledge-base documents.\n"
    "\n"
    "The user gives you a TITLE and a BODY. Return ONLY valid JSON:\n"
    '{"summary": "..."}\n'
    "\n"
    "The summary must:\n"
    "- be 2-3 sentences, factual, written in plain past tense\n"
    "- name specific people / projects / dates if they appear in the body\n"
    "- never invent facts, never include \"this document discusses\" filler\n"
    "- never exceed 60 words"
)


_TAG_SYSTEM_PROMPT = (
    "You propose tags for a personal-knowledge-base document.\n"
    "\n"
    "Inputs: TITLE, SUMMARY, EXISTING_VOCAB (tags already used in the corpus),\n"
    "CURRENT_TAGS (tags already on this doc).\n"
    "\n"
    "Return ONLY valid JSON:\n"
    '{"tags": ["tag1", "tag2", "tag3"]}\n'
    "\n"
    "Rules:\n"
    "- propose 3 to 5 tags\n"
    "- prefer tags from EXISTING_VOCAB; only propose new tags when no existing tag fits\n"
    "- lowercase, hyphen-separated (e.g. \"interview-prep\", \"company-acme\")\n"
    "- never propose tags already in CURRENT_TAGS\n"
    "- never propose more than 5 tags\n"
    "- never propose tags about file format (pdf, docx, transcript) — those are tracked elsewhere\n"
    "- never propose tags about timing (recent, old, last-week)"
)


# Wave G2-b — concept entity extraction (spec §3 D3 / §8). The extractor
# *backend* lives here (transport, JSON-mode, retry) so it shares one place with
# ``summarize`` / ``propose_tags``; the concept-extraction *logic* (chunking,
# canonicalization, position-finding, per-doc cap, never-raise) lives in
# :mod:`brain.graph_rag.extract`. ``type`` is constrained to the four concept
# entity types — people are derived for free from the participants pipeline and
# are deliberately NOT extracted here (spec §17b decision 2: "people excluded").
_EXTRACT_SYSTEM_PROMPT = (
    "You extract the salient non-person CONCEPT entities from a "
    "personal-knowledge-base document.\n"
    "\n"
    "Return ONLY valid JSON:\n"
    '{"entities": [{"name": "...", "type": "topic"}]}\n'
    "\n"
    "type MUST be exactly one of: org, project, tool, topic.\n"
    "Use the entity's surface form exactly as it appears in the text for name.\n"
    "\n"
    "Type rules:\n"
    "- org: a company or provider whose hosted service or platform you consume "
    "or integrate with — e.g. a payments, identity, data-warehouse, or cloud "
    "provider. Use the company name.\n"
    "- tool: software you run, deploy, operate, import, or build with — a "
    "framework, library, language, database, monitoring agent, or server.\n"
    "- project: a named initiative or effort. Keep the FULL name including a "
    'leading word like "Project" (return the whole "Project <name>" form, never '
    "just the bare name).\n"
    "- topic: a central, durable theme or subject area the document is about, "
    "usually one or two words.\n"
    "\n"
    "Topic guidance:\n"
    "- Capture the few themes the text frames as central. Look for "
    "importance-signaling language — examples (not an exhaustive list) include "
    '"the main topic", "the recurring theme", "the headline", "dominated the '
    'discussion", "a major focus was", "central to the conversation", "we kept '
    'coming back to", or "came up repeatedly" — and any similar phrasing that '
    "marks something as important, as well as the core subject the document "
    "centers on.\n"
    "- Also capture the core subject word that a named effort or platform is "
    'about — the domain word inside phrases like a "<X> effort", "<X> '
    'initiative", "<X> platform", or "<X> stack" (extract <X> as the topic).\n'
    "- Return roughly 1-3 topics, and prefer the short theme word over a long "
    "phrase (the one- or two-word theme, not a verbose feature description).\n"
    "\n"
    "Never extract:\n"
    "- people or person names (they are tracked separately)\n"
    "- dates, times, or file formats\n"
    "- document-structure references (PDF, chapter, section, page, table, "
    "figure, appendix, heading)\n"
    "- generic activities or events (meetings, reviews, sprints, workshops)\n"
    "- incidental UI or implementation nouns, or one-off mentions that are not a "
    "central theme\n"
    "- vague container words (platform, service, system, dashboard) on their own\n"
    "\n"
    "CRITICAL: Extract ONLY entities that appear LITERALLY in THIS text. Copy the "
    "name exactly as written. Never invent a name, never add a name that is not "
    "in the text, and never copy a name from these instructions or from a "
    "previous document.\n"
    "\n"
    "The bracketed words in the FORMAT example below are PLACEHOLDERS showing the "
    "JSON shape only. They are NOT real entities — never output them.\n"
    "FORMAT (schematic — replace each placeholder with a real name from the "
    "text, or omit it):\n"
    'JSON: {"entities": [{"name": "<the hosted provider named in the text>", '
    '"type": "org"}, {"name": "Project <the effort named in the text>", '
    '"type": "project"}, {"name": "<the software tool named in the text>", '
    '"type": "tool"}, {"name": "<the central theme of the text>", '
    '"type": "topic"}]}\n'
    "\n"
    "When THIS text contains no org, project, tool, or topic entities, return an "
    "empty list. Do NOT fill it with examples or guesses:\n"
    'JSON: {"entities": []}'
)


# Wave G2-f — on-demand theme synthesis (spec §6b step 4 / §17b decision 7).
# Opt-in (``--synthesize``); best-effort and never required for retrieval.
_GROUP_SUMMARY_SYSTEM_PROMPT = (
    "You write a one-to-two sentence synthesis of a cluster of related topics "
    "from a personal knowledge base.\n"
    "\n"
    "Inputs: PERSON/SCOPE (the person the themes are about, if any), TOPICS "
    "(the cluster's key entities), and REPRESENTATIVE DOCUMENTS (their titles).\n"
    "\n"
    "Return ONLY valid JSON:\n"
    '{"summary": "..."}\n'
    "\n"
    "Rules:\n"
    "- 1-2 sentences, factual, plain past tense\n"
    "- name the specific topics that tie the cluster together\n"
    "- never invent facts, never exceed 50 words"
)

# Token budget for the concept-extraction completion. Larger than the
# summary/tag budget (256) because a document can yield a long entity list.
_EXTRACT_NUM_PREDICT = 1024


@dataclass(frozen=True)
class SummaryResult:
    """One enrichment summary. Stored byte-for-byte on ``documents.summary``.

    ``model`` is the model fingerprint (e.g. ``"llama3.1:8b"``) so the
    post-ingest hook can persist it onto ``documents.summary_model`` and
    ``brain enrich --backfill --remodel`` can detect drift after a model
    swap (without ``--remodel``, backfill is NULL-only and ignores
    fingerprint mismatches).
    """

    summary: str
    model: str


@dataclass(frozen=True)
class TagProposal:
    """The LLM's proposed tag set for one document, partitioned by novelty.

    ``existing`` are tags already used somewhere in the corpus; ``new`` are
    tags the LLM proposed that aren't in the vocabulary yet (already
    rate-limited to ≤``max_new`` entries — default 1 — by
    :meth:`OllamaEnricher.propose_tags`).
    """

    existing: list[str]
    new: list[str]


class OllamaEnricher:
    """Thin wrapper over Ollama's ``/api/chat`` endpoint with JSON mode.

    One instance, one model. Callers (post-ingest hook, ``brain enrich``,
    ``brain tag --auto``) instantiate via :func:`make_enricher` and reuse
    the same instance for the lifetime of a CLI invocation.

    Public surface:
        - ``summarize(title, content)`` → :class:`SummaryResult`
        - ``propose_tags(title, summary, existing_vocab, current_tags, max_new=1)``
            → :class:`TagProposal`
        - ``extract_entities(text)`` → ``list[Any]`` (raw concept-entity
            candidates; the concept-extraction *logic* lives in
            :mod:`brain.graph_rag.extract`)
        - ``summarize_group(person, entity_names, doc_titles)`` → ``str | None``
            (best-effort theme synthesis; never raises)
        - ``count_tokens(text)`` → int (tiktoken ``cl100k_base``)
        - ``model`` (read-only attribute) → the model fingerprint
    """

    def __init__(
        self,
        *,
        host: str,
        model: str,
        client: httpx.Client | None = None,
        timeout: float = 60.0,
        max_input_tokens: int = 4000,
        keep_alive: str = _DEFAULT_KEEP_ALIVE,
    ) -> None:
        self._host = host
        self._model = model
        self._max_input_tokens = max_input_tokens
        self._keep_alive = keep_alive
        self._tokenizer = tiktoken.get_encoding("cl100k_base")
        if client is not None:
            self._client = client
        else:
            self._client = httpx.Client(
                base_url=host, timeout=httpx.Timeout(timeout)
            )

    @property
    def model(self) -> str:
        return self._model

    def count_tokens(self, text: str) -> int:
        """Return the number of tokens in ``text`` per ``cl100k_base``."""
        return len(self._tokenizer.encode(text))

    def truncate_to_tokens(self, text: str, max_tokens: int) -> str:
        """Return the head of ``text`` truncated to its first ``max_tokens`` tokens.

        Head-only truncation using the SAME ``cl100k_base`` tokenizer as
        :meth:`count_tokens`, so a caller's truncation boundary is consistent with
        the chunk budgeting that also goes through ``count_tokens`` — the concept
        extractor's input head cap (perf Fix C, 2026-05-24) reuses this so its cap
        and its per-chunk token sizing agree. The full text is returned unchanged
        when it already fits. ``max_tokens`` must be positive. Cheap: one encode +
        one decode.
        """
        if max_tokens < 1:
            raise ValueError(
                f"max_tokens must be a positive integer (got {max_tokens})"
            )
        ids = self._tokenizer.encode(text)
        if len(ids) <= max_tokens:
            return text
        return self._tokenizer.decode(ids[:max_tokens])

    def _truncate_to_budget(self, text: str) -> str:
        """Truncate ``text`` to this enricher's summary input budget (head-only).

        Delegates to :meth:`truncate_to_tokens` with ``self._max_input_tokens``
        (the per-instance summary cap, default 4000): the opening of a doc is the
        highest-signal portion for transcripts, emails, and notes alike.
        """
        return self.truncate_to_tokens(text, self._max_input_tokens)

    def summarize(self, title: str, content: str) -> SummaryResult:
        """Return a 2-3 sentence summary of ``content``.

        Calls ``/api/chat`` with ``format='json'`` and a system prompt that
        constrains the model to emit ``{"summary": "..."}``. On JSON parse
        failure or missing key, retries ONCE with the same prompt. Second
        failure raises :class:`EnrichmentError`. Connection / 5xx errors
        raise :class:`OllamaUnavailable` immediately (no retry — Ollama-down
        is the common case and we want to fail fast so the post-ingest hook
        can skip).
        """
        truncated = self._truncate_to_budget(content)
        user_message = f"TITLE: {title}\n\nBODY:\n{truncated}"
        body = self._chat_with_retry(
            system=_SUMMARY_SYSTEM_PROMPT,
            user=user_message,
            schema_keys=("summary",),
        )
        summary = body["summary"]
        if not isinstance(summary, str) or not summary.strip():
            raise EnrichmentError(
                f"summarize: model returned non-string / empty summary: {body!r}"
            )
        return SummaryResult(summary=summary.strip(), model=self._model)

    def propose_tags(
        self,
        *,
        title: str,
        summary: str,
        existing_vocab: list[str],
        current_tags: list[str],
        max_new: int = 1,
    ) -> TagProposal:
        """Return 3-5 proposed tags partitioned into existing-vocab + new.

        Returned tags are normalized via :func:`brain.tags.normalize_tags`,
        de-duplicated against ``current_tags`` (we never re-propose tags
        already on the doc), banned-format tags are dropped at the Python
        layer (D20 belt-and-braces), and the ``new`` partition is truncated
        to the first ``max_new`` entries (default 1) per the R2 mitigation
        in the wave plan.
        """
        if max_new < 0:
            raise ValueError(f"max_new must be non-negative (got {max_new})")
        # Normalize the vocab + current-tags so the LLM sees canonical forms
        # and the post-call partitioning compares normalized to normalized.
        vocab_normalized = normalize_tags(existing_vocab)
        current_normalized = set(normalize_tags(current_tags))
        user_message = (
            f"TITLE: {title}\n\n"
            f"SUMMARY: {summary}\n\n"
            f"EXISTING_VOCAB: {json.dumps(vocab_normalized)}\n"
            f"CURRENT_TAGS: {json.dumps(sorted(current_normalized))}"
        )
        body = self._chat_with_retry(
            system=_TAG_SYSTEM_PROMPT,
            user=user_message,
            schema_keys=("tags",),
        )
        raw_tags = body["tags"]
        if not isinstance(raw_tags, list) or not all(
            isinstance(t, str) for t in raw_tags
        ):
            raise EnrichmentError(
                f"propose_tags: model returned non-list-of-str tags: {body!r}"
            )
        normalized = normalize_tags(raw_tags)
        # Drop banned formats (D20) BEFORE partitioning so they can't sneak
        # into either bucket.
        normalized = [t for t in normalized if t not in _BANNED_AUTO_TAGS]
        # Drop anything already on the doc — no point proposing what's there.
        normalized = [t for t in normalized if t not in current_normalized]
        vocab_set = set(vocab_normalized)
        existing: list[str] = []
        new: list[str] = []
        for tag in normalized:
            if tag in vocab_set:
                existing.append(tag)
            else:
                new.append(tag)
        return TagProposal(existing=existing, new=new[:max_new])

    def extract_entities(self, text: str) -> list[Any]:
        """Return the model's raw concept-entity candidates for one text block.

        One ``/api/chat`` JSON-mode round-trip with the concept-extraction
        system prompt. Returns the model's ``entities`` array verbatim — a list
        whose individual elements the caller (:class:`brain.graph_rag.extract.
        OllamaExtractor`) validates, canonicalizes, positions, dedups, and caps.
        This method does NOT chunk: the extractor sizes each ``text`` block to
        the model context and calls once per chunk.

        Raises :class:`OllamaUnavailable` / :class:`EnrichmentError` on transport
        / malformed-response failures exactly like :meth:`summarize`. The
        never-raise boundary is the :class:`~brain.graph_rag.extract.
        OllamaExtractor`, which catches these so a gated ingest never breaks
        (spec §17b decision 7 / §7 never-raise discipline).
        """
        body = self._chat_with_retry(
            system=_EXTRACT_SYSTEM_PROMPT,
            user=f"TEXT:\n{text}",
            schema_keys=("entities",),
            num_predict=_EXTRACT_NUM_PREDICT,
        )
        entities = body["entities"]
        if not isinstance(entities, list):
            raise EnrichmentError(
                f"extract_entities: model returned non-list entities: {body!r}"
            )
        return entities

    def summarize_group(
        self,
        *,
        person: str | None,
        entity_names: list[str],
        doc_titles: list[str],
    ) -> str | None:
        """Best-effort one-to-two sentence synthesis of a theme group.

        Used by the G2-f ``--synthesize`` path (spec §6b step 4 / §17b decision
        7): opt-in, default-off, and **never required for retrieval**. Returns
        the synthesized text, or ``None`` (logging a WARN) when Ollama is
        unavailable / times out / returns invalid JSON / yields an empty
        summary. NEVER raises — mirroring the GraphSyncer + enrich never-raise
        discipline so a retrieval path never becomes a hard live-Ollama
        dependency.
        """
        scope = f" {person}" if person else " (none)"
        user_message = (
            f"PERSON/SCOPE:{scope}\n"
            f"TOPICS: {json.dumps(entity_names)}\n"
            f"REPRESENTATIVE DOCUMENTS: {json.dumps(doc_titles)}"
        )
        try:
            body = self._chat_with_retry(
                system=_GROUP_SUMMARY_SYSTEM_PROMPT,
                user=user_message,
                schema_keys=("summary",),
            )
        except EnrichmentError as exc:
            # OllamaUnavailable is an EnrichmentError subclass, so this single
            # clause covers transport failure AND malformed-JSON-twice.
            _logger.warning(
                "summarize_group: synthesis failed (%s); returning summary=None",
                exc,
            )
            return None
        summary = body["summary"]
        if not isinstance(summary, str) or not summary.strip():
            _logger.warning(
                "summarize_group: model returned empty / non-string summary; "
                "returning summary=None"
            )
            return None
        return summary.strip()

    def _chat_with_retry(
        self,
        *,
        system: str,
        user: str,
        schema_keys: tuple[str, ...],
        num_predict: int = 256,
    ) -> dict[str, Any]:
        """Issue an ``/api/chat`` JSON-mode call with one retry on parse failure.

        Returns the parsed JSON object on success. Raises
        :class:`OllamaUnavailable` on transient transport errors (no retry
        — fail fast so callers can skip). Raises :class:`EnrichmentError`
        when two consecutive attempts fail JSON parsing / schema validation.
        """
        last_error: Exception | None = None
        current_num_predict = num_predict
        for attempt in (1, 2):
            try:
                response_text = self._chat_once(
                    system=system, user=user, num_predict=current_num_predict
                )
            except OllamaUnavailable:
                # Transient — propagate immediately, no retry.
                raise
            try:
                parsed = json.loads(response_text)
            except json.JSONDecodeError as exc:
                last_error = exc
                # Truncation: the model exhausted ``num_predict`` mid-string.
                # Same budget would re-truncate deterministically; double it
                # for the retry so the next call can complete. Schema/non-dict
                # failures don't trigger the bump.
                if "Unterminated" in exc.msg:
                    current_num_predict *= 2
                _logger.debug(
                    "enricher chat attempt %d: JSON decode failed (%s); response=%r",
                    attempt,
                    exc,
                    response_text[:200],
                )
                continue
            if not isinstance(parsed, dict):
                last_error = EnrichmentError(
                    f"chat returned non-object JSON: {parsed!r}"
                )
                continue
            missing = [k for k in schema_keys if k not in parsed]
            if missing:
                last_error = EnrichmentError(
                    f"chat response missing required keys {missing}: {parsed!r}"
                )
                continue
            return parsed
        # Both attempts failed.
        assert last_error is not None
        raise EnrichmentError(
            f"enrichment failed after 2 attempts: {last_error}"
        ) from last_error

    def _chat_once(self, *, system: str, user: str, num_predict: int = 256) -> str:
        """Single ``/api/chat`` round-trip returning the inner content string.

        Returns the ``message.content`` field verbatim so the caller can
        ``json.loads`` it. Maps transport-layer failures to
        :class:`OllamaUnavailable` (CLAUDE.md "no bare except" — only
        ``httpx.HTTPError`` and ``ValueError`` are caught here, matching the
        embedder's pattern). ``num_predict`` caps the completion length
        (default 256 for summary/tag; the concept extractor passes a larger
        budget for long entity lists).
        """
        request_body = {
            "model": self._model,
            "stream": False,
            "format": "json",
            "keep_alive": self._keep_alive,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "options": {"temperature": 0.0, "num_predict": num_predict},
        }
        try:
            response = self._client.post("/api/chat", json=request_body)
            response.raise_for_status()
            payload = response.json()
        except httpx.HTTPStatusError as exc:
            status = exc.response.status_code if exc.response is not None else 0
            body_preview = (
                exc.response.text[:200] if exc.response is not None else "<no body>"
            )
            if status >= 500:
                raise OllamaUnavailable(
                    f"Ollama returned HTTP {status}: {body_preview}"
                ) from exc
            # 4xx — permanent (bad model name, malformed request).
            raise EnrichmentError(
                f"Ollama returned HTTP {status}: {body_preview}"
            ) from exc
        except (httpx.ConnectError, httpx.ConnectTimeout, httpx.ReadTimeout) as exc:
            raise OllamaUnavailable(f"Ollama unreachable: {exc}") from exc
        except httpx.HTTPError as exc:
            raise OllamaUnavailable(f"Ollama transport error: {exc}") from exc
        except ValueError as exc:
            # json.JSONDecodeError is a ValueError — a 200 OK with non-JSON
            # body leaks as a raw decode error otherwise.
            raise EnrichmentError(
                f"Ollama returned non-JSON envelope: {exc}"
            ) from exc
        message = payload.get("message") if isinstance(payload, dict) else None
        if not isinstance(message, dict):
            raise EnrichmentError(
                f"Ollama response missing 'message': {payload!r}"
            )
        content = message.get("content")
        if not isinstance(content, str):
            raise EnrichmentError(
                f"Ollama message.content is not a string: {message!r}"
            )
        return content


def make_enricher(cfg: Config) -> OllamaEnricher:
    """Factory — same shape as :func:`brain.embeddings.make_embedder`.

    Reads ``cfg.enrich_model`` / ``cfg.ollama_host`` /
    ``cfg.enrich_max_input_tokens`` / ``cfg.enrich_timeout_seconds`` and
    always returns an :class:`OllamaEnricher` (single-backend wave). Tests
    pass a fake via direct construction or by substituting at the call site;
    production code goes through this factory.
    """
    return OllamaEnricher(
        host=cfg.ollama_host,
        model=cfg.enrich_model,
        timeout=cfg.enrich_timeout_seconds,
        max_input_tokens=cfg.enrich_max_input_tokens,
        keep_alive=cfg.ollama_keep_alive,
    )
