"""Local-Ollama enrichment: per-document summary + tag proposals.

One module, two consumers: the post-ingest auto-summary hook in
``brain.ingest.__init__`` and the interactive ``brain tag --auto`` flow in
``brain.cli``. Both go through :class:`OllamaEnricher` so HTTP transport,
JSON-mode handling, timeouts, and retry policy live in one place.

Ollama is the only backend in Wave Q1-D — no Claude Haiku / OpenAI / Voyage
surface. Model is configurable via ``BRAIN_ENRICH_MODEL`` (default
``llama3.1:8b``). The class reuses the ``httpx.Client`` transport pattern
from :class:`brain.embeddings._OllamaEmbedderBase` but does NOT subclass it:
the embedder hits ``/api/embed`` for vectors and the enricher hits
``/api/chat`` for JSON completions, so a shared parent would carry no
shared logic.

Model upgrade semantics
-----------------------
``documents.summary_model`` records the model fingerprint of every persisted
summary. The post-ingest hook and ``brain enrich --backfill`` both treat
"existing summary AND ``summary_model == cfg.enrich_model``" as up-to-date;
when the user upgrades ``BRAIN_ENRICH_MODEL`` (e.g. ``llama3.1:8b`` →
``llama3.2:8b``), every doc whose stored summary was generated by the OLD
model is automatically re-enriched on next ingest / next backfill run. The
behavior is keyed on ``OllamaEnricher.model`` (the property), so callers
that pass a fake enricher in tests can control the comparison without
monkey-patching the production module.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Any

import httpx
import tiktoken

from .config import Config
from .errors import EnrichmentError, OllamaUnavailable
from .tags import normalize_tags

_logger = logging.getLogger(__name__)

# D20 — banned auto-tag formats. These are ``documents.content_type`` values
# (or close synonyms) that the LLM should never propose as semantic tags.
# Belt-and-braces with the prompt: a prompt-injection / model drift case that
# slipped one past the prompt is still filtered at the Python layer. Stored
# casefold-lower-hyphen-normalized so the post-``normalize_tags`` comparison
# is a direct membership check.
_BANNED_AUTO_TAGS = frozenset(
    {
        "pdf",
        "transcript",
        "email",
        "email-thread",
        "note",
        "docx",
        "markdown",
        "text",
        "krisp-action-items",
    }
)


_SUMMARY_SYSTEM_PROMPT = (
    "You write 2-3 sentence summaries of personal-knowledge-base documents.\n"
    "\n"
    "The user gives you a TITLE and a BODY. Return ONLY valid JSON:\n"
    '{"summary": "..."}\n'
    "\n"
    "The summary must:\n"
    "- be 2-3 sentences, factual, written in plain past tense\n"
    "- name specific people / projects / dates if they appear in the body\n"
    "- never invent facts, never include \"this document discusses\" filler\n"
    "- never exceed 60 words"
)


_TAG_SYSTEM_PROMPT = (
    "You propose tags for a personal-knowledge-base document.\n"
    "\n"
    "Inputs: TITLE, SUMMARY, EXISTING_VOCAB (tags already used in the corpus),\n"
    "CURRENT_TAGS (tags already on this doc).\n"
    "\n"
    "Return ONLY valid JSON:\n"
    '{"tags": ["tag1", "tag2", "tag3"]}\n'
    "\n"
    "Rules:\n"
    "- propose 3 to 5 tags\n"
    "- prefer tags from EXISTING_VOCAB; only propose new tags when no existing tag fits\n"
    "- lowercase, hyphen-separated (e.g. \"interview-prep\", \"company-acme\")\n"
    "- never propose tags already in CURRENT_TAGS\n"
    "- never propose more than 5 tags\n"
    "- never propose tags about file format (pdf, docx, transcript) — those are tracked elsewhere\n"
    "- never propose tags about timing (recent, old, last-week)"
)


@dataclass(frozen=True)
class SummaryResult:
    """One enrichment summary. Stored byte-for-byte on ``documents.summary``.

    ``model`` is the model fingerprint (e.g. ``"llama3.1:8b"``) so the
    post-ingest hook can persist it onto ``documents.summary_model`` and
    ``brain enrich --backfill --remodel`` can detect drift after a model
    swap (without ``--remodel``, backfill is NULL-only and ignores
    fingerprint mismatches).
    """

    summary: str
    model: str


@dataclass(frozen=True)
class TagProposal:
    """The LLM's proposed tag set for one document, partitioned by novelty.

    ``existing`` are tags already used somewhere in the corpus; ``new`` are
    tags the LLM proposed that aren't in the vocabulary yet (already
    rate-limited to ≤``max_new`` entries — default 1 — by
    :meth:`OllamaEnricher.propose_tags`).
    """

    existing: list[str]
    new: list[str]


class OllamaEnricher:
    """Thin wrapper over Ollama's ``/api/chat`` endpoint with JSON mode.

    One instance, one model. Callers (post-ingest hook, ``brain enrich``,
    ``brain tag --auto``) instantiate via :func:`make_enricher` and reuse
    the same instance for the lifetime of a CLI invocation.

    Public surface:
        - ``summarize(title, content)`` → :class:`SummaryResult`
        - ``propose_tags(title, summary, existing_vocab, current_tags, max_new=1)``
            → :class:`TagProposal`
        - ``count_tokens(text)`` → int (tiktoken ``cl100k_base``)
        - ``model`` (read-only attribute) → the model fingerprint
    """

    def __init__(
        self,
        *,
        host: str,
        model: str,
        client: httpx.Client | None = None,
        timeout: float = 60.0,
        max_input_tokens: int = 4000,
    ) -> None:
        self._host = host
        self._model = model
        self._max_input_tokens = max_input_tokens
        self._tokenizer = tiktoken.get_encoding("cl100k_base")
        if client is not None:
            self._client = client
        else:
            self._client = httpx.Client(
                base_url=host, timeout=httpx.Timeout(timeout)
            )

    @property
    def model(self) -> str:
        return self._model

    def count_tokens(self, text: str) -> int:
        """Return the number of tokens in ``text`` per ``cl100k_base``."""
        return len(self._tokenizer.encode(text))

    def _truncate_to_budget(self, text: str) -> str:
        """Return the head of ``text`` truncated to ``self._max_input_tokens``.

        Head-only: the opening of a doc is the highest-signal portion for
        transcripts, emails, and notes alike. Cheap (one encode + decode).
        """
        ids = self._tokenizer.encode(text)
        if len(ids) <= self._max_input_tokens:
            return text
        return self._tokenizer.decode(ids[: self._max_input_tokens])

    def summarize(self, title: str, content: str) -> SummaryResult:
        """Return a 2-3 sentence summary of ``content``.

        Calls ``/api/chat`` with ``format='json'`` and a system prompt that
        constrains the model to emit ``{"summary": "..."}``. On JSON parse
        failure or missing key, retries ONCE with the same prompt. Second
        failure raises :class:`EnrichmentError`. Connection / 5xx errors
        raise :class:`OllamaUnavailable` immediately (no retry — Ollama-down
        is the common case and we want to fail fast so the post-ingest hook
        can skip).
        """
        truncated = self._truncate_to_budget(content)
        user_message = f"TITLE: {title}\n\nBODY:\n{truncated}"
        body = self._chat_with_retry(
            system=_SUMMARY_SYSTEM_PROMPT,
            user=user_message,
            schema_keys=("summary",),
        )
        summary = body["summary"]
        if not isinstance(summary, str) or not summary.strip():
            raise EnrichmentError(
                f"summarize: model returned non-string / empty summary: {body!r}"
            )
        return SummaryResult(summary=summary.strip(), model=self._model)

    def propose_tags(
        self,
        *,
        title: str,
        summary: str,
        existing_vocab: list[str],
        current_tags: list[str],
        max_new: int = 1,
    ) -> TagProposal:
        """Return 3-5 proposed tags partitioned into existing-vocab + new.

        Returned tags are normalized via :func:`brain.tags.normalize_tags`,
        de-duplicated against ``current_tags`` (we never re-propose tags
        already on the doc), banned-format tags are dropped at the Python
        layer (D20 belt-and-braces), and the ``new`` partition is truncated
        to the first ``max_new`` entries (default 1) per the R2 mitigation
        in the wave plan.
        """
        if max_new < 0:
            raise ValueError(f"max_new must be non-negative (got {max_new})")
        # Normalize the vocab + current-tags so the LLM sees canonical forms
        # and the post-call partitioning compares normalized to normalized.
        vocab_normalized = normalize_tags(existing_vocab)
        current_normalized = set(normalize_tags(current_tags))
        user_message = (
            f"TITLE: {title}\n\n"
            f"SUMMARY: {summary}\n\n"
            f"EXISTING_VOCAB: {json.dumps(vocab_normalized)}\n"
            f"CURRENT_TAGS: {json.dumps(sorted(current_normalized))}"
        )
        body = self._chat_with_retry(
            system=_TAG_SYSTEM_PROMPT,
            user=user_message,
            schema_keys=("tags",),
        )
        raw_tags = body["tags"]
        if not isinstance(raw_tags, list) or not all(
            isinstance(t, str) for t in raw_tags
        ):
            raise EnrichmentError(
                f"propose_tags: model returned non-list-of-str tags: {body!r}"
            )
        normalized = normalize_tags(raw_tags)
        # Drop banned formats (D20) BEFORE partitioning so they can't sneak
        # into either bucket.
        normalized = [t for t in normalized if t not in _BANNED_AUTO_TAGS]
        # Drop anything already on the doc — no point proposing what's there.
        normalized = [t for t in normalized if t not in current_normalized]
        vocab_set = set(vocab_normalized)
        existing: list[str] = []
        new: list[str] = []
        for tag in normalized:
            if tag in vocab_set:
                existing.append(tag)
            else:
                new.append(tag)
        return TagProposal(existing=existing, new=new[:max_new])

    def _chat_with_retry(
        self, *, system: str, user: str, schema_keys: tuple[str, ...]
    ) -> dict[str, Any]:
        """Issue an ``/api/chat`` JSON-mode call with one retry on parse failure.

        Returns the parsed JSON object on success. Raises
        :class:`OllamaUnavailable` on transient transport errors (no retry
        — fail fast so callers can skip). Raises :class:`EnrichmentError`
        when two consecutive attempts fail JSON parsing / schema validation.
        """
        last_error: Exception | None = None
        for attempt in (1, 2):
            try:
                response_text = self._chat_once(system=system, user=user)
            except OllamaUnavailable:
                # Transient — propagate immediately, no retry.
                raise
            try:
                parsed = json.loads(response_text)
            except json.JSONDecodeError as exc:
                last_error = exc
                _logger.debug(
                    "enricher chat attempt %d: JSON decode failed (%s); response=%r",
                    attempt,
                    exc,
                    response_text[:200],
                )
                continue
            if not isinstance(parsed, dict):
                last_error = EnrichmentError(
                    f"chat returned non-object JSON: {parsed!r}"
                )
                continue
            missing = [k for k in schema_keys if k not in parsed]
            if missing:
                last_error = EnrichmentError(
                    f"chat response missing required keys {missing}: {parsed!r}"
                )
                continue
            return parsed
        # Both attempts failed.
        assert last_error is not None
        raise EnrichmentError(
            f"enrichment failed after 2 attempts: {last_error}"
        ) from last_error

    def _chat_once(self, *, system: str, user: str) -> str:
        """Single ``/api/chat`` round-trip returning the inner content string.

        Returns the ``message.content`` field verbatim so the caller can
        ``json.loads`` it. Maps transport-layer failures to
        :class:`OllamaUnavailable` (CLAUDE.md "no bare except" — only
        ``httpx.HTTPError`` and ``ValueError`` are caught here, matching the
        embedder's pattern).
        """
        request_body = {
            "model": self._model,
            "stream": False,
            "format": "json",
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "options": {"temperature": 0.0, "num_predict": 256},
        }
        try:
            response = self._client.post("/api/chat", json=request_body)
            response.raise_for_status()
            payload = response.json()
        except httpx.HTTPStatusError as exc:
            status = exc.response.status_code if exc.response is not None else 0
            body_preview = (
                exc.response.text[:200] if exc.response is not None else "<no body>"
            )
            if status >= 500:
                raise OllamaUnavailable(
                    f"Ollama returned HTTP {status}: {body_preview}"
                ) from exc
            # 4xx — permanent (bad model name, malformed request).
            raise EnrichmentError(
                f"Ollama returned HTTP {status}: {body_preview}"
            ) from exc
        except (httpx.ConnectError, httpx.ConnectTimeout, httpx.ReadTimeout) as exc:
            raise OllamaUnavailable(f"Ollama unreachable: {exc}") from exc
        except httpx.HTTPError as exc:
            raise OllamaUnavailable(f"Ollama transport error: {exc}") from exc
        except ValueError as exc:
            # json.JSONDecodeError is a ValueError — a 200 OK with non-JSON
            # body leaks as a raw decode error otherwise.
            raise EnrichmentError(
                f"Ollama returned non-JSON envelope: {exc}"
            ) from exc
        message = payload.get("message") if isinstance(payload, dict) else None
        if not isinstance(message, dict):
            raise EnrichmentError(
                f"Ollama response missing 'message': {payload!r}"
            )
        content = message.get("content")
        if not isinstance(content, str):
            raise EnrichmentError(
                f"Ollama message.content is not a string: {message!r}"
            )
        return content


def make_enricher(cfg: Config) -> OllamaEnricher:
    """Factory — same shape as :func:`brain.embeddings.make_embedder`.

    Reads ``cfg.enrich_model`` / ``cfg.ollama_host`` /
    ``cfg.enrich_max_input_tokens`` / ``cfg.enrich_timeout_seconds`` and
    always returns an :class:`OllamaEnricher` (single-backend wave). Tests
    pass a fake via direct construction or by substituting at the call site;
    production code goes through this factory.
    """
    return OllamaEnricher(
        host=cfg.ollama_host,
        model=cfg.enrich_model,
        timeout=cfg.enrich_timeout_seconds,
        max_input_tokens=cfg.enrich_max_input_tokens,
    )
