"""BACKWARD-COMPATIBILITY FIREWALL — do not edit this file.

``brain search --json`` is consumed positionally (``jq '.[0].id'``, the
``consult-brain`` skill, user shell scripts). MCP ``brain_search`` returns a
dict whose top-level shape already broke once in Q1-C. Both contracts are
frozen here, and every additive feature must route around them:

* CLI ``--json`` stays a BARE LIST of objects with exactly seven keys.
* MCP ``brain_search`` keeps ``session_id`` + ``results``, and each result
  object keeps exactly the same seven keys.

If a change makes a test in this file fail, the change is wrong — not the
test. New metadata belongs behind ``--meta`` (CLI) or on additive top-level
MCP keys.

All fixture data is synthetic.
"""
from __future__ import annotations

import json
import os
from collections.abc import Iterator
from typing import Any

import psycopg
import pytest
from typer.testing import CliRunner

from brain import mcp_server
from brain.cli import app
from brain.config import Config
from brain.ingest import ExtractedDoc, ingest_document
from brain.search import SearchDiagnostics

TEST_DATABASE_URL = os.environ.get(
    "TEST_DATABASE_URL",
    "postgresql://brain:brain@localhost:5434/second_brain_test",
)

#: The frozen public shape of one search result on BOTH surfaces.
SEVEN_KEYS = {
    "id",
    "title",
    "source_kind",
    "snippet",
    "score",
    "content_type",
    "tags",
}


def _seed(conn: psycopg.Connection[Any], embedder: Any, count: int = 3) -> None:
    """Ingest ``count`` synthetic documents all matching the word 'quarterly'.

    Bodies differ per document: ``documents.content_hash`` is UNIQUE, so
    identical bodies would dedup into one row.
    """
    for i in range(count):
        ingest_document(
            conn,
            embedder=embedder,
            doc=ExtractedDoc(
                title=f"Quarterly note {i}",
                content=f"The quarterly review covered budget and hiring {i}.",
                content_type="note",
                source_path=None,
                metadata={},
            ),
            source_kind="manual",
            source_external_id=f"manual:quarterly-{i}",
            tags=["planning"],
        )


@pytest.fixture
def mcp_state(
    monkeypatch: pytest.MonkeyPatch,
    test_db: psycopg.Connection[Any],  # noqa: ARG001 — keeps the schema fresh
    fake_embedder: Any,
) -> Iterator[mcp_server._State]:
    state = mcp_server._State(
        cfg=Config(database_url=TEST_DATABASE_URL),
        embedder=fake_embedder,
    )
    monkeypatch.setattr(mcp_server, "_state", state)
    yield state


# ---------------------------------------------------------------------------
# CLI — the bare list
# ---------------------------------------------------------------------------


def test_default_json_is_still_a_bare_list_of_seven_key_objects(
    test_db: psycopg.Connection[Any],
    fake_embedder: Any,
    patch_embedder: Any,
) -> None:
    """THE CONTRACT: ``brain search --json`` is a list of seven-key objects."""
    # Arrange
    _seed(test_db, fake_embedder)
    patch_embedder(fake_embedder)

    # Act
    result = CliRunner().invoke(app, ["search", "quarterly", "--fts-only", "--json"])

    # Assert
    assert result.exit_code == 0, result.output
    payload = json.loads(result.stdout)
    assert isinstance(payload, list)
    assert payload, "the seeded corpus must produce at least one hit"
    assert set(payload[0]) == SEVEN_KEYS


def test_json_stdout_is_parseable_with_footer_enabled(
    test_db: psycopg.Connection[Any],
    fake_embedder: Any,
    patch_embedder: Any,
) -> None:
    """The piping guarantee: metadata never lands on ``--json`` stdout."""
    # Arrange
    _seed(test_db, fake_embedder)
    patch_embedder(fake_embedder)

    # Act
    result = CliRunner().invoke(app, ["search", "quarterly", "--fts-only", "--json"])

    # Assert — stdout parses cleanly no matter what stderr carries.
    assert result.exit_code == 0, result.output
    assert isinstance(json.loads(result.stdout), list)


def test_zero_result_json_is_an_empty_list(
    test_db: psycopg.Connection[Any],  # noqa: ARG001 — an empty corpus is the point
    fake_embedder: Any,
    patch_embedder: Any,
) -> None:
    """An off-corpus query still emits ``[]``, not an envelope."""
    # Arrange
    patch_embedder(fake_embedder)

    # Act
    result = CliRunner().invoke(
        app, ["search", "nonexistentterm", "--fts-only", "--json"]
    )

    # Assert
    assert result.exit_code == 0, result.output
    assert json.loads(result.stdout) == []


# ---------------------------------------------------------------------------
# MCP — session_id + results, seven keys each
# ---------------------------------------------------------------------------


def test_mcp_brain_search_keeps_session_id_and_results(
    mcp_state: mcp_server._State,  # noqa: ARG001 — installs the fake state
    test_db: psycopg.Connection[Any],
    fake_embedder: Any,
) -> None:
    """``session_id`` and ``results`` must both survive every additive change."""
    # Arrange
    _seed(test_db, fake_embedder)

    # Act
    payload = mcp_server.brain_search(query="quarterly", fts_only=True)

    # Assert
    assert "session_id" in payload
    assert "results" in payload
    assert isinstance(payload["results"], list)


def test_mcp_brain_search_envelope_has_exactly_the_expected_keys(
    mcp_state: mcp_server._State,  # noqa: ARG001 — installs the fake state
    test_db: psycopg.Connection[Any],
    fake_embedder: Any,
) -> None:
    """Pin the whole envelope, not just the presence of the two original keys.

    Three MCP tests used to assert ``set(payload.keys()) == {"session_id",
    "results"}``. F5 relaxed them to superset checks so the additive metadata
    keys could land — correct in itself, but it left *nothing* asserting the
    exact set, so an accidentally-leaked internal field would have gone
    unnoticed.

    "Additive keys only" is a contract about what may be added *deliberately*,
    not licence for the payload to grow silently. Adding a key is fine; adding
    one without updating this assertion is not.

    The expected set is derived from ``search_meta_json`` rather than hardcoded
    so this test pins the *envelope shape* and cannot drift from the metadata
    helper — the helper's own key names are covered by its dedicated tests.
    """
    # Arrange
    _seed(test_db, fake_embedder)

    # Act
    payload = mcp_server.brain_search(query="quarterly", fts_only=True)

    # Assert
    meta_keys = set(
        mcp_server.search_meta_json(SearchDiagnostics(), returned=0, facets=None)
    )
    assert set(payload.keys()) == {"session_id", "results"} | meta_keys


def test_mcp_result_objects_keep_exactly_seven_keys(
    mcp_state: mcp_server._State,  # noqa: ARG001 — installs the fake state
    test_db: psycopg.Connection[Any],
    fake_embedder: Any,
) -> None:
    """Result objects are byte-identical in shape to the CLI's list entries."""
    # Arrange
    _seed(test_db, fake_embedder)

    # Act
    payload = mcp_server.brain_search(query="quarterly", fts_only=True)

    # Assert
    assert payload["results"], "the seeded corpus must produce at least one hit"
    assert set(payload["results"][0]) == SEVEN_KEYS
