"""Drift guards for the rendered-wiki GIF and its browser-capture regenerator.

``docs/assets/wiki.gif`` is a BROWSER capture of the rendered Quartz wiki — the
graph view, backlinks panel, and People Hub — embedded near the top of
``docs/vault-and-wiki.md`` and regenerated by ``bin/brain-wiki-gif`` (which
drives the frame capture via ``bin/brain-wiki-gif-capture.cjs``).

Unlike the vhs terminal GIFs guarded by ``tests/test_docs_assets.py``, this one
provisions a real Postgres + Quartz build and drives a headless browser, so the
regenerator is the highest-risk asset script in the repo. These tests keep the
asset, the docs embed, and the regenerators from drifting apart, and — since the
regenerator stands up a throwaway stack around the *real* CLI — assert the
safety invariants that keep it off the prod / demo / test databases and the
user's real vault.
"""
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS = REPO_ROOT / "docs" / "assets"
DOCS_PAGE = REPO_ROOT / "docs" / "vault-and-wiki.md"

WIKI_GIF = ASSETS / "wiki.gif"
WIKI_SCRIPT = REPO_ROOT / "bin" / "brain-wiki-gif"
WIKI_CAPTURE = REPO_ROOT / "bin" / "brain-wiki-gif-capture.cjs"

# docs budget (bytes). Mirrors the 3 MB ceiling the regenerator warns at.
WIKI_MAX_BYTES = 3 * 1024 * 1024
# The GIF is scaled to this width by the regenerator's ffmpeg step.
WIKI_GIF_WIDTH = 1200

# The isolated sandbox the regenerator is allowed to touch, and the databases it
# must NEVER connect to (prod / demo / test). The forbidden checks look for a
# connection form (``:PORT/`` in a DB URL) rather than the bare number, so the
# script may still name those ports in a comment explaining what it avoids.
WIKI_SANDBOX_PORT = "55444"
WIKI_PROJECT = "brain-wiki-gif"
WIKI_DB_NAME = "second_brain_wiki_gif"
FORBIDDEN_DB_URLS = (":55432/", ":55433/", ":5434/")


# --------------------------------------------------------------------------- #
# Existence + budget                                                          #
# --------------------------------------------------------------------------- #
def test_wiki_gif_exists_and_is_nonempty() -> None:
    assert WIKI_GIF.is_file(), f"missing wiki GIF: {WIKI_GIF}"
    assert WIKI_GIF.stat().st_size > 0, f"empty GIF: {WIKI_GIF}"


def test_wiki_gif_within_budget() -> None:
    assert WIKI_GIF.stat().st_size <= WIKI_MAX_BYTES, (
        f"{WIKI_GIF.name} exceeds the {WIKI_MAX_BYTES} byte docs budget"
    )


def test_wiki_gif_is_a_gif() -> None:
    with WIKI_GIF.open("rb") as fh:
        header = fh.read(6)
    assert header in (b"GIF87a", b"GIF89a"), f"{WIKI_GIF.name} is not a GIF"


def test_wiki_gif_is_scaled_to_target_width() -> None:
    # GIF logical-screen descriptor: bytes 6-7 are the canvas width (LE uint16).
    with WIKI_GIF.open("rb") as fh:
        head = fh.read(8)
    width = head[6] | (head[7] << 8)
    assert width == WIKI_GIF_WIDTH, (
        f"{WIKI_GIF.name} is {width}px wide, expected {WIKI_GIF_WIDTH}px"
    )


# --------------------------------------------------------------------------- #
# Regenerators exist + are executable                                         #
# --------------------------------------------------------------------------- #
def test_regenerators_are_executable() -> None:
    for script in (WIKI_SCRIPT, WIKI_CAPTURE):
        assert script.is_file(), f"missing regenerator: {script}"
        assert os.access(script, os.X_OK), f"regenerator not executable: {script}"


# --------------------------------------------------------------------------- #
# docs/vault-and-wiki.md embeds the GIF + points at the regenerator           #
# --------------------------------------------------------------------------- #
def test_docs_page_embeds_the_wiki_gif() -> None:
    text = DOCS_PAGE.read_text(encoding="utf-8")
    assert "](assets/wiki.gif)" in text, (
        "docs/vault-and-wiki.md no longer embeds the wiki GIF"
    )


def test_docs_page_points_at_the_regenerator() -> None:
    text = DOCS_PAGE.read_text(encoding="utf-8")
    assert "bin/brain-wiki-gif" in text, (
        "docs/vault-and-wiki.md does not reference the regenerator"
    )


# --------------------------------------------------------------------------- #
# Regenerator safety invariants (it drives the REAL CLI + a real Postgres)    #
# --------------------------------------------------------------------------- #
def test_script_targets_only_the_sandbox_database() -> None:
    text = WIKI_SCRIPT.read_text(encoding="utf-8")
    # The DB URL is composed from the sandbox port + db-name variables (localhost).
    assert f'DB_PORT="{WIKI_SANDBOX_PORT}"' in text, "wiki-gif script lost its :55444 port"
    assert f'DB_NAME="{WIKI_DB_NAME}"' in text, "wiki-gif script lost its isolated db name"
    assert "localhost:${DB_PORT}/${DB_NAME}" in text, (
        "wiki-gif script no longer composes its DB URL from the sandbox port + db name"
    )
    for db_url in FORBIDDEN_DB_URLS:
        assert db_url not in text, (
            f"wiki-gif script connects to a forbidden DB ({db_url}) — prod/demo/test"
        )


def test_capture_script_carries_no_database_urls() -> None:
    text = WIKI_CAPTURE.read_text(encoding="utf-8")
    for db_url in FORBIDDEN_DB_URLS + (f":{WIKI_SANDBOX_PORT}/",):
        assert db_url not in text, f"capture script should carry no DB URL ({db_url})"


def test_script_scopes_teardown_and_uses_named_volume() -> None:
    text = WIKI_SCRIPT.read_text(encoding="utf-8")
    assert WIKI_PROJECT in text, "wiki-gif script lost its isolated project name"
    assert WIKI_SANDBOX_PORT in text, "wiki-gif script no longer pins port 55444"
    # Teardown scoped to our own project, with a named volume (never a bind mount).
    assert "down -v" in text, "wiki-gif script does not tear its sandbox volume down"
    assert '-p "$PROJECT"' in text or f"-p {WIKI_PROJECT}" in text, (
        "wiki-gif script teardown is not scoped to the brain-wiki-gif project"
    )
    assert "/var/lib/postgresql/data" in text, "wiki-gif script lost its pg data volume"
    assert "./data/postgres" not in text, (
        "wiki-gif script must not bind-mount the prod-style ./data/postgres path"
    )


def test_script_overrides_db_and_vault_via_env() -> None:
    text = WIKI_SCRIPT.read_text(encoding="utf-8")
    assert "export DATABASE_URL=" in text, (
        "wiki-gif script must export DATABASE_URL so it wins over any repo-root .env"
    )
    assert "export BRAIN_VAULT_PATH=" in text, (
        "wiki-gif script must redirect BRAIN_VAULT_PATH away from the real vault"
    )


def test_script_fails_closed_on_wrong_target() -> None:
    """The script must hard-abort unless it targets its own sandbox + tempdir."""
    text = WIKI_SCRIPT.read_text(encoding="utf-8")
    assert "refusing to run" in text, "wiki-gif script has no fail-closed guard"
    assert "exit 1" in text, "wiki-gif script has no fail-closed abort"


def test_script_never_references_the_real_vault_or_workspace() -> None:
    text = WIKI_SCRIPT.read_text(encoding="utf-8")
    # No mention of the default real vault dir, nor of a `.quartz` workspace.
    assert "brain-vault" not in text, (
        "wiki-gif script references the real ~/brain-vault vault dir"
    )
    assert ".quartz" not in text, (
        "wiki-gif script references a real .quartz Quartz workspace"
    )
    # The vault + workspace both live under the tempdir workdir.
    assert 'WORKDIR="${TMPDIR:-/tmp}/brain-wiki-gif"' in text, (
        "wiki-gif script's workdir is not a $TMPDIR sandbox"
    )
    assert 'BRAIN_VAULT_PATH="$VAULT_DIR"' in text
    assert 'VAULT_DIR="$WORKDIR/vault"' in text
    # No operational reference to a home-directory vault / workspace.
    for bad in (
        "--vault ~",
        '--vault "$HOME',
        "--quartz-dir ~",
        '--quartz-dir "$HOME',
        "BRAIN_VAULT_PATH=~",
        'BRAIN_VAULT_PATH="$HOME',
    ):
        assert bad not in text, f"wiki-gif script points at a home-dir path ({bad!r})"


def test_script_seeds_only_synthetic_content() -> None:
    text = WIKI_SCRIPT.read_text(encoding="utf-8")
    # Synthetic Larkspur corpus with the reserved example.com email domain, plus
    # an explicit zero-PII marker in the header.
    assert "@example.com" in text, "wiki-gif corpus lost its synthetic email domain"
    assert "Larkspur" in text, "wiki-gif corpus lost its synthetic Larkspur universe"
    assert "ZERO PII" in text, "wiki-gif script lost its zero-PII marker"
