"""Fast-path ignore rules: which frontmatter keys the fingerprint may skip.

The fingerprint (see :mod:`brain.wiki.fastpath_manifest`) encodes only the
*structural* frontmatter fields.  Every other key a document carries has to be
classified before a fingerprint may be trusted: either it demonstrably cannot
change rendered HTML — in which case it is ignored — or it is unknown, and the
edit is forced down the full-build path.  Unknown keys failing closed is the
whole safety property; see the spec's "paranoid by design" section.

**Why this module exists.** That ignore set used to be a 75-entry literal in
the shipped package.  Fifty-two of those entries are generic (brain's own
identity/provenance keys, ingest metadata, ordinary free-form note fields);
the remaining twenty-three were frontmatter keys observed in one particular
vault, namespaced under product and vendor names.  Shipping them put private
identifiers into a public PyPI wheel, and no user other than that vault's
owner was served by them.  The split here is therefore not a refactor for its
own sake: generic keys stay in the package, corpus-specific keys move to a
file the vault owner controls.

**Layering.** :data:`DEFAULT_IGNORED_FIELDS` ships in the package and is the
whole story for a user who configures nothing.  A vault may add to it — never
replace it — with a ``.brain-fastpath-ignore`` file at its root::

    # one frontmatter key per line; '#' starts a comment
    acme_ledger_id          # a literal key
    acme_sweep_*            # a glob covers a whole namespaced family

Globs (``*``, ``?``, ``[...]``) are matched case-sensitively with
:func:`fnmatch.fnmatchcase`.

**Why the vault root, and not ``.quartz/``.** ``<vault>/.quartz/`` is a Quartz
workspace clone that ``brain wiki install --force`` deletes outright, so a
config file there would not survive a reinstall.  The vault root is the user's
own content directory.

**Failure modes, and why they are the safe ones.** An absent file is not an
error — it is the documented zero-config state, and yields the default.  A
file that is present but unreadable or malformed raises
:class:`IgnoreRulesError`, which the classifier turns into a full build.  Both
directions of change are safe by construction: adding rules can only move keys
from "raises" to "ignored", and an ignored key is absent from the canonical
blob, so the value it computes is the one the full build already stored;
removing rules can only move keys from "ignored" to "raises", which costs
extra full builds and never a stale answer.
"""
from __future__ import annotations

from dataclasses import dataclass
from fnmatch import fnmatchcase
from pathlib import Path

from brain.wiki.errors import BrainWikiError

IGNORE_FILE_NAME = ".brain-fastpath-ignore"

_GLOB_CHARS = frozenset("*?[")


class IgnoreRulesError(BrainWikiError):
    """Raised when a vault's ignore file exists but cannot be read or parsed."""


DEFAULT_IGNORED_FIELDS: frozenset[str] = frozenset({
    # Identity / dedup metadata
    "id", "external_id", "content_type", "source", "source_path",
    "source_template_id", "source_template_name", "vault_path", "canonical", "hash",
    # Ingest provenance
    "ai_assisted", "autogenerated", "last_reviewed", "collected_by", "owner",
    "organization_id", "organization_name",
    # Generic workflow / quota tracking
    "check_grace_period", "hits", "hours_saved_by_workflow", "hours_saved_today",
    "hours_saved_totals", "mandate", "proposal_expiration",
    "proposal_follow_up_reminders", "quota", "report_usage", "reset_ai_quotas",
    "sidebar_position", "status", "trial_expiration_check",
    # Krisp/Slack/Gmail metadata
    "participants", "duration_min", "thread_id", "channel", "attendees",
    "to", "from", "subject", "schedule",
    # Free-form metadata not rendered
    "context", "keywords", "notes", "predecessor", "principle", "purview",
    "render", "seo", "sweep", "where", "with", "wrote",
})


@dataclass(frozen=True)
class IgnoreRules:
    """Literal keys plus glob patterns whose frontmatter deltas are non-structural."""

    literals: frozenset[str]
    patterns: tuple[str, ...]
    origin: str

    def matches(self, key: str) -> bool:
        """True when ``key`` is covered by a literal or a glob pattern."""
        if key in self.literals:
            return True
        return any(fnmatchcase(key, pat) for pat in self.patterns)


DEFAULT_IGNORE_RULES = IgnoreRules(
    literals=DEFAULT_IGNORED_FIELDS,
    patterns=(),
    origin="built-in default",
)


def parse_ignore_file(text: str) -> tuple[frozenset[str], tuple[str, ...]]:
    """Parse ignore-file ``text`` into (literals, patterns)."""
    literals: set[str] = set()
    patterns: list[str] = []
    for lineno, raw in enumerate(text.splitlines(), start=1):
        entry = raw.split("#", 1)[0].strip()
        if not entry:
            continue
        if any(ch.isspace() for ch in entry):
            raise IgnoreRulesError(
                f"line {lineno}: frontmatter keys cannot contain whitespace"
            )
        if _GLOB_CHARS & set(entry):
            patterns.append(entry)
        else:
            literals.add(entry)
    return frozenset(literals), tuple(patterns)


def load_ignore_rules(vault_root: Path | None) -> IgnoreRules:
    """Load ignore rules for ``vault_root``, unioned onto the built-in default."""
    if vault_root is None:
        return DEFAULT_IGNORE_RULES
    path = vault_root / IGNORE_FILE_NAME
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return DEFAULT_IGNORE_RULES
    except OSError as exc:
        raise IgnoreRulesError(f"cannot read ignore file at {path}: {exc}") from exc
    except UnicodeDecodeError as exc:
        raise IgnoreRulesError(f"ignore file at {path} is not valid UTF-8: {exc}") from exc
    try:
        literals, patterns = parse_ignore_file(text)
    except IgnoreRulesError as exc:
        raise IgnoreRulesError(f"{path}: {exc}") from exc
    return IgnoreRules(
        literals=DEFAULT_IGNORED_FIELDS | literals,
        patterns=patterns,
        origin=str(path),
    )
