"""Auto-generate ``<vault>/daily/index.md`` from the dailies on disk.

Phase 4.1 of the Wiki UX Overhaul. The home note's "Daily notes" door
points at ``daily/`` — Quartz resolves a folder reference to
``daily/index`` if and only if a markdown file exists at that path.
Without :func:`regenerate_daily_index`, the door is a 404.

Contract:

* Walks ``<vault>/daily/<YYYY>/<YYYY-MM-DD>.md`` recursively (any depth
  is tolerated, but the brain CLI only writes year-folder children) and
  collects every ``.md`` file whose stem matches ``YYYY-MM-DD``.
  ``index.md`` itself is excluded so a re-run of the regen doesn't
  feed itself.
* Sorted reverse-chronological by filename. The filename is the
  canonical truth (matches the slug Quartz emits, matches what the
  user expects to see) — frontmatter ``date`` would be a second
  truth-source that could drift.
* Body = ``- [[YYYY-MM-DD]]`` per line, newest first. Wiki-link form
  uses the bare date stem so Quartz's ``markdownLinkResolution:
  shortest`` resolves to the right path under ``daily/<YYYY>/``
  without the regen having to know about year folders.
* Frontmatter: ``id`` and ``created`` are preserved across re-runs
  (read from the existing file when present); ``updated`` is bumped
  only when the body changed; ``autogenerated: true`` flags the
  file as a brain-managed artifact users shouldn't hand-edit.
* Idempotent: when the body matches what's already on disk, the file
  is left untouched (no ``updated`` churn, no atomic write). A test
  asserts byte-identical output across two consecutive regens.
* Empty case: when no daily notes exist, the function does NOT write
  ``index.md``. Combined with the home-page hide-if-empty
  transformer this gives a coherent "no dailies → no door" UX. A
  pre-existing ``index.md`` is left in place — deleting it would
  surprise users who hand-curated the file before running the regen.

The atomic write uses :func:`brain.vault._atomic.atomic_write_text`
so a crash mid-write can never leave a half-written index visible to
Quartz's watcher.
"""
from __future__ import annotations

import re
import uuid
from datetime import UTC, datetime
from pathlib import Path

import yaml

from ._atomic import atomic_write_text
from .frontmatter import dump_frontmatter, parse_frontmatter
from .paths import strip_md_extension

# Filename stem of a daily note: ``YYYY-MM-DD``. Anchored on both ends
# so a stray ``2026-04-29-rough-thoughts.md`` (a manually-named note
# under ``daily/``) doesn't get hoisted into the index.
_DAILY_STEM_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

_INDEX_FILENAME = "index.md"


def _list_daily_notes(daily_dir: Path) -> list[Path]:
    """Return every ``YYYY-MM-DD.md`` daily note under ``daily_dir``.

    Recursive — the brain CLI nests daily notes under
    ``daily/<YYYY>/`` but a user who's flattened the structure
    (or never year-folded their pre-2026 notes) is also supported. The
    filename ``index.md`` is excluded so a stale auto-generated index
    can't recursively feed itself.

    Returns the empty list when ``daily_dir`` doesn't exist (the brain
    vault scaffolds it via ``init_vault`` but a user pointing at an
    unmanaged folder might not have one yet).
    """
    if not daily_dir.is_dir():
        return []
    out: list[Path] = []
    for path in daily_dir.rglob("*.md"):
        if path.name == _INDEX_FILENAME:
            continue
        if not path.is_file():
            continue
        if _DAILY_STEM_RE.match(path.stem):
            out.append(path)
    return out


def _build_index_body(daily_paths: list[Path], *, vault_path: Path) -> str:
    """Return the body text for ``daily/index.md`` from ``daily_paths``.

    Reverse-chronological by filename stem (``YYYY-MM-DD`` lex-sorts
    correctly as date order). Each line is a path-form-aliased wiki
    link — ``[[daily/<year>/<stem>|<stem>]]`` — matching the canonical
    shape that :func:`brain.vault.link_rewrite.rewrite_wiki_links`
    produces for resolved vault links.

    Why path-form, not bare stem? Earlier prototype used
    ``[[<stem>]]`` and relied on Quartz's ``markdownLinkResolution:
    shortest`` to resolve the date-shaped target. That worked at the
    Quartz level, but the post-write ``brain vault sync`` ran the link
    rewriter over the body and replaced every bare stem with the path-
    form alias. The next ``brain daily`` invocation then saw a body
    mismatch (regen wanted bare stem, disk had path form), triggered
    a rewrite, and bumped ``updated:`` — losing idempotency and
    sending the watcher into a rebuild loop on every invocation.
    Emitting the path-form here makes the regen output already
    canonical, so the sync step is a no-op and consecutive runs
    leave the file byte-identical.

    The body opens with a ``# Daily notes`` heading and a one-line
    preamble — Quartz uses the heading as the page title and the
    preamble as the breadcrumb-friendly first paragraph. A trailing
    newline closes the file in the conventional Unix way.
    """
    # Sort by stem desc — but keep the resolved path alongside so the
    # path-form alias can be emitted without a second filesystem walk.
    rels: list[tuple[str, str]] = []
    for p in daily_paths:
        try:
            rel = p.resolve().relative_to(vault_path.resolve())
        except ValueError:
            # Defensive: ``rglob`` shouldn't surface a path outside
            # ``daily_dir``, but a symlinked vault could in theory.
            # Skip rather than crash.
            continue
        # POSIX form so the wiki link round-trips on Windows too. Strip
        # ``.md`` to match what the link rewriter emits — shared helper
        # in :mod:`brain.vault.paths` so the homepage / people / daily
        # renderers cannot drift on the canonical link-target shape.
        rels.append((p.stem, strip_md_extension(rel.as_posix())))
    rels.sort(key=lambda t: t[0], reverse=True)

    lines = [
        "# Daily notes",
        "",
        (
            "All daily notes, newest first. "
            "This page is auto-generated — run `brain daily` to refresh it."
        ),
        "",
    ]
    for stem, posix in rels:
        lines.append(f"- [[{posix}|{stem}]]")
    lines.append("")
    return "\n".join(lines)


def _read_existing_metadata(target: Path) -> tuple[str | None, str | None, str | None]:
    """Return ``(id, created, body)`` from an existing index.md, or ``None``s.

    Used to preserve ``id`` and ``created`` across re-runs (so the
    auto-generated row keeps a stable DB identity even when the body
    changes), and to short-circuit the rewrite when the body hasn't
    changed (so the on-disk file stays byte-identical and the watcher
    doesn't fire a needless rebuild).

    Failure modes — missing file, malformed YAML, structurally invalid
    frontmatter — return ``(None, None, None)`` so the caller treats
    the situation as "regenerate from scratch." This is safe: a
    corrupt index re-emerges with a fresh id; the user can always
    rebind it via ``brain edit`` if they had hand-edits worth saving
    (auto-generated files explicitly carry ``autogenerated: true`` to
    discourage that workflow).
    """
    if not target.is_file():
        return (None, None, None)
    try:
        text = target.read_text(encoding="utf-8")
    except OSError:
        return (None, None, None)
    try:
        fields, body = parse_frontmatter(text)
    except (ValueError, yaml.YAMLError):
        return (None, None, None)
    raw_id = fields.get("id")
    raw_created = fields.get("created")
    return (
        raw_id if isinstance(raw_id, str) else None,
        raw_created if isinstance(raw_created, str) else None,
        body,
    )


def regenerate_daily_index(vault_path: Path) -> bool:
    """Regenerate ``<vault>/daily/index.md`` from the dailies on disk.

    Returns ``True`` if the file was written (or rewritten), ``False``
    if the regen was a no-op (body unchanged, or no dailies to index).

    Atomic — a crash mid-write leaves the previous ``index.md`` (if
    any) intact. Idempotent — two consecutive calls against an
    unchanged ``daily/`` produce a byte-identical file on disk.

    Empty case: no daily notes ⇒ no write. A pre-existing
    ``index.md`` is left in place rather than deleted; the user's
    hand-curated file (if any) survives. The home-page hide-if-empty
    transformer is the layer that reflects "no dailies" in the UI.
    """
    daily_dir = vault_path / "daily"
    target = daily_dir / _INDEX_FILENAME

    daily_paths = _list_daily_notes(daily_dir)
    if not daily_paths:
        return False

    body = _build_index_body(daily_paths, vault_path=vault_path)

    existing_id, existing_created, existing_body = _read_existing_metadata(target)
    if existing_body is not None and existing_body == body:
        # No content drift — skip rewrite to keep the file byte-identical
        # and the watcher quiet.
        return False

    now_iso = datetime.now(UTC).isoformat(timespec="seconds")
    doc_id = existing_id if existing_id else str(uuid.uuid4())
    created = existing_created if existing_created else now_iso
    fields: dict[str, object] = {
        "id": doc_id,
        "title": "Daily notes",
        "created": created,
        "updated": now_iso,
        "tags": ["daily", "index"],
        "kind": "vault",
        "content_type": "note",
        "autogenerated": True,
    }
    target.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(target, dump_frontmatter(fields, body))
    return True
